package dev.jsinco.brewery.format;

import dev.jsinco.brewery.configuration.Config;

public class TimeFormatHeader {

    public static String get() {
        return switch (Config.config().language().toLanguageTag()) {
            case "ru" -> russian();
            default -> english();
        };
    }

    private static String english() {
        return "#  +-----------------------------------------------------------------------------------+\n"
             + "#  | This file is for specifying how time intervals should be formatted and displayed. |\n"
             + "#  +-----------------------------------------------------------------------------------+\n"
             + "#\n"
             + "#  PLACEHOLDERS (will be replaced with the corresponding values):\n"
             + "#\n"
             + "#    Modular (leftover) values:\n"
             + "#      These show the value of a unit after larger units have been subtracted.\n"
             + "#      Available: <ticks>, <seconds>, <minutes>, <hours>, <days>, <years>, <decades>\n"
             + "#      Example: in \"1 hour 45 minutes\", <minutes> = 45.\n"
             + "#\n"
             + "#    Total values (independent of higher units):\n"
             + "#      These show the complete value of a unit, ignoring larger breakdowns.\n"
             + "#      Available: <ticks-total>, <seconds-total>, <minutes-total>, <hours-total>, <days-total>, <years-total>\n"
             + "#      Example: in \"1 hour 45 minutes\", <minutes-total> = 105.\n"
             + "#\n"
             + "#  CONDITIONAL BLOCKS:\n"
             + "#\n"
             + "#    <if-unit>...</if-unit>    ...Content is only shown if that unit is NOT zero\n"
             + "#    <if-!unit>...</if-!unit>  ...Content is only shown if that unit IS zero\n"
             + "#\n"
             + "#    Example: \"<if-hours-total><hours-total>:</if-hours-total><minutes>:<seconds>\"\n"
             + "#      => hours are only added for times above or equal to one hour (e.g. 1:45:00)\n"
             + "#\n"
             + "#  PLURALIZATION:\n"
             + "#\n"
             + "#    [text]  ...Shown only if the last number before it is NOT 1\n"
             + "#    {text}  ...Shown only if the last number before it IS 1\n"
             + "#\n"
             + "#    Example: \"<minutes> minute[s]\" => 1 minute / 2 minutes\n"
             + "#\n"
             + "#    [text]<n>  ...Shown only if the last number before it is NOT n\n"
             + "#    {text}<n>  ...Shown only if the last number before it IS n\n"
             + "#\n"
             + "#    Example: \"<ticks-total> {is five}<5>[is not five]<5>\" => 5 is five / 3 is not five\n"
             + "#\n"
             + "#    [text]<a-b>  ...Shown only if the last number before it is NOT in range a-b\n"
             + "#    {text}<a-b>  ...Shown only if the last number before it IS in range a-b\n"
             + "#\n"
             + "#    Example: \"<ticks-total> {is in range}<2-4>[is not in range]<2-4>\" => 3 is in range / 5 is not in range\n"
             + "#\n"
             + "#    You can use double angled brackets to check for the last prior digit, not the whole number:\n"
             + "#     => \"{text}<<a-b>>\"  ...Shown only if the last DIGIT before it is in range a-b\n"
             + "#\n"
             + "#    Pluralization blocks can be nested with double and triple brackets, as they take higher priority:\n"
             + "#     => \"<ticks> {{{text}<<5>>}}<0-100>\"  ...Shows \"text\" behind numbers that end on 5 in range 0 - 100\n"
             + "#\n"
             + "#  EXAMPLES:\n"
             + "#\n"
             + "#    \"2 days, 0 hours, 17 minutes and 1 second\", \"45 minutes and 30 seconds\":\n"
             + "#\n"
             + "#      \"<if-days-total><days-total> day[s], <if-!hours><hours> hour[s], </if-!hours></if-days-total>\n"
             + "#       <if-hours><hours> hour[s], </if-hours><minutes> minute[s] and <seconds> second[s]\"\n"
             + "#\n"
             + "#    \"2 days, 17 minutes and 1 second\", \"45 minutes and 30 seconds\":\n"
             + "#\n"
             + "#      \"<if-days-total><days-total> day[s], </if-days-total><if-hours><hours> hour[s], </if-hours>\n"
             + "#       <minutes> minute[s] and <seconds> second[s]\"\n"
             + "#\n"
             + "#    \"26:45:30\", \"25:00\", \"00:05\":\n"
             + "#\n"
             + "#      \"<if-hours-total><hours-total>:</if-hours-total><minutes>:<seconds>\"\n"
             + "#\n"
             + "#    \"85:45\", \"00:15\":\n"
             + "#\n"
             + "#      \"<minutes-total>:<seconds>\"\n"
             + "#\n";
    }

    private static String russian() {
        return "#  +-----------------------------------------------------------------------------------+\n"
             + "#  |       В этом файле можно настроить формат и отображение интервалов времени        |\n"
             + "#  +-----------------------------------------------------------------------------------+\n"
             + "#\n"
             + "#  ПЛЕЙСХОЛДЕРЫ (автоматически заменяются соответствующими значениями):\n"
             + "#\n"
             + "#    Модульные (остаточные) значения:\n"
             + "#      Отображают значения единицы времени (далее - юнита) без учёта единиц более высокого уровня.\n"
             + "#      Доступны: <ticks>, <seconds>, <minutes>, <hours>, <days>, <years>, <decades>\n"
             + "#      Пример: в \"1 час 45 минут\", <minutes> равняется 45.\n"
             + "#\n"
             + "#    Абсолютные значения (независимые):\n"
             + "#      Отображают полное значение юнита, без разбивки на более крупные уровни.\n"
             + "#      Доступны: <ticks-total>, <seconds-total>, <minutes-total>, <hours-total>, <days-total>, <years-total>\n"
             + "#      Пример: в \"1 час 45 минут\", <minutes-total> равняется 105.\n"
             + "#\n"
             + "#  УСЛОВНЫЕ БЛОКИ:\n"
             + "#\n"
             + "#    <if-юнит>...</if-юнит>    ...Отображается только если указанный юнит НЕ = 0\n"
             + "#    <if-!юнит>...</if-!юнит>  ...Отображается только если указанный юнит == 0\n"
             + "#\n"
             + "#    Пример: \"<if-hours-total><hours-total>:</if-hours-total><minutes>:<seconds>\"\n"
             + "#      => часы отображаются только если время равно или выше 1 часа (например 1:45:00)\n"
             + "#\n"
             + "#  МНОЖЕСТВЕННЫЕ ЧИСЛА:\n"
             + "#\n"
             + "#    [текст]  ...Отображается только если идущее перед этим число НЕ = 1\n"
             + "#    {текст}  ...Отображается только если идущее перед этим число == 1\n"
             + "#\n"
             + "#    Пример: \"<minutes> minute[s]\" => 1 minute / 2 minutes\n"
             + "#\n"
             + "#    [текст]<n>  ...Отображается только если идущее перед этим число НЕ = n\n"
             + "#    {текст}<n>  ...Отображается только если идущее перед этим число == n\n"
             + "#\n"
             + "#    Пример: \"<ticks-total> {пятёрка}<5>[не пятёрка]<5>\" => 5 пятёрка / 3 не пятёрка\n"
             + "#\n"
             + "#    [текст]<a-b>  ...Отображается только если идущее перед этим число НЕ в диапазоне a-b\n"
             + "#    {текст}<a-b>  ...Отображается только если идущее перед этим число ЕСТЬ в диапазоне a-b\n"
             + "#\n"
             + "#    Пример: \"<ticks-total> {между 2 и 4}<2-4>[не между 2 и 4]<2-4>\" => 3 между 2 и 4 / 5 не между 2 и 4\n"
             + "#\n"
             + "#    Можно сделать треугольные скобки двойными, чтобы работать лишь с ЦИФРАМИ, а не целыми ЧИСЛАМИ:\n"
             + "#     => \"{текст}<<a-b>>\"  ...Отображается только если идущая перед этим ЦИФРА есть в диапазоне a-b\n"
             + "#        <<1-3>> => подойдут 1-3, 11-13, 21-23 и т.д.\n"
             + "#\n"
             + "#    Блоки Множественности можно использовать с двойными и тройными скобками, поскольку у них более высокий приоритет:\n"
             + "#     => \"<ticks> {{{текст}<<5>>}}<0-100>\"  ...Покажет \"текст\" после чисел, которые оканчиваются на цифру 5 в пределах диапазона 0-100\n"
             + "#\n"
             + "#  ГОТОВЫЕ ПРИМЕРЫ (на английском):\n"
             + "#\n"
             + "#    \"2 days, 0 hours, 17 minutes and 1 second\", \"45 minutes and 30 seconds\":\n"
             + "#\n"
             + "#      \"<if-days-total><days-total> day[s], <if-!hours><hours> hour[s], </if-!hours></if-days-total>\n"
             + "#       <if-hours><hours> hour[s], </if-hours><minutes> minute[s] and <seconds> second[s]\"\n"
             + "#\n"
             + "#    \"2 days, 17 minutes and 1 second\", \"45 minutes and 30 seconds\":\n"
             + "#\n"
             + "#      \"<if-days-total><days-total> day[s], </if-days-total><if-hours><hours> hour[s], </if-hours>\n"
             + "#       <minutes> minute[s] and <seconds> second[s]\"\n"
             + "#\n"
             + "#    \"26:45:30\", \"25:00\", \"00:05\":\n"
             + "#\n"
             + "#      \"<if-hours-total><hours-total>:</if-hours-total><minutes>:<seconds>\"\n"
             + "#\n"
             + "#    \"85:45\", \"00:15\":\n"
             + "#\n"
             + "#      \"<minutes-total>:<seconds>\"\n"
             + "#\n";
    }

}
