plugins {
    application

    alias(libs.plugins.neoforged.gradle.common)
}

group = "dev.jsinco.brewery.datagenerator"
version = project.findProperty("version")!!

repositories {
    mavenCentral()
    maven("https://maven.neoforged.net/releases")
}

dependencies {
    implementation("net.minecraft:client:${project.findProperty("minecraft.version")!!}:client-extra")
    implementation(libs.gson)
}

tasks {
    application {
        mainClass = "dev.jsinco.brewery.datagenerator.DataGenerator"
    }

    getByName<JavaExec>("run") {
        args = listOf(rootProject.projectDir.resolve("core/src/autogenerated/resources").absolutePath)
    }
}