plugins {
    application
    id("net.neoforged.gradle.common") version "7.0.181"
}

group = "dev.jsinco.brewery.datagenerator"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
    maven("https://maven.neoforged.net/releases")
}

dependencies {
    implementation("net.minecraft:client:1.21.4:client-extra")
    implementation("com.google.code.gson:gson:2.12.1")
}

tasks {
    application {
        mainClass = "dev.jsinco.brewery.datagenerator.DataGenerator"
    }

    getByName<JavaExec>("run") {
        args = listOf(rootProject.projectDir.resolve("src/autogenerated/resources").absolutePath)
    }
}